# Generated by Django 5.2 on 2025-04-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_badge', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_old_price', models.IntegerField()),
                ('product_category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('home_appliance', 'Home Appliance'), ('books', 'Books'), ('toys', 'Toys'), ('sports', 'Sports'), ('beauty', 'Beauty'), ('others', 'Others')], max_length=100)),
                ('product_reviews', models.IntegerField(default=0)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
